package db.operaciones;

/**
 *
 * @author usuario
 */
public class diseñotienda extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(diseñotienda.class.getName());

    /**
     * Creates new form diseñotienda
     */
    public diseñotienda() {
        // 1. Llama al método automático controlado por el diseñador .form
        initComponents();

        // 2. Registra los eventos de manera segura
        conectarBotones();
    }

    private void conectarBotones() {
        // Evitamos que falle si IntelliJ aún no ha sincronizado el archivo .form
        if (jButton2 == null) {
            return;
        }

        // --- CONEXIÓN DE BOTÓN REGISTRAR ---
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    String marca = jTextField1.getText();
                    String modelo = jTextField2.getText();
                    int camara = Integer.parseInt(jTextField3.getText());
                    int almacenamiento = Integer.parseInt(jTextField4.getText());
                    int ram = Integer.parseInt(jTextField5.getText());
                    int bateria = Integer.parseInt(jTextField6.getText());
                    double precio = Double.parseDouble(jTextField7.getText());

                    model.celular nuevoCelular = new model.celular(marca, modelo, camara, bateria);
                    model.inventario nuevoInventario = new model.inventario(0, almacenamiento, precio, ram);

                    TiendaDAO dao = new TiendaDAO();
                    boolean exito = dao.registrarCelularCompleto(nuevoCelular, nuevoInventario);

                    if (exito) {
                        javax.swing.JOptionPane.showMessageDialog(null, "¡Celular registrado con éxito en la base de datos Neon!");
                        jTextField1.setText(""); jTextField2.setText(""); jTextField3.setText("");
                        jTextField4.setText(""); jTextField5.setText(""); jTextField6.setText(""); jTextField7.setText("");
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(null, "Hubo un problema al guardar en la base de datos.");
                    }
                } catch (NumberFormatException ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Por favor, llena los campos numéricos con números válidos.");
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(null, "Error al registrar: " + ex.getMessage());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        // NOTA: Deja este espacio completamente en blanco en el editor de texto.
        // Al realizar el paso de abajo en la pestaña 'diseñotienda.form',
        // IntelliJ generará e inyectará los componentes automáticamente aquí.
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setText("");
        String criterio = jTextField8.getText().trim();
        if (criterio.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor, escribe la marca que deseas buscar.");
            return;
        }
        TiendaDAO dao = new TiendaDAO();
        jTextArea1.setText(dao.obtenerFiltradoPorMarcaTexto(criterio));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextArea1.setText("");
        TiendaDAO dao = new TiendaDAO();
        jTextArea1.setText(dao.obtenerInventarioCompletoTexto());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new diseñotienda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}